// src/App.tsx
/* esLint-disable */

import React, { useState } from 'react';
import './App.css';
import { Nav, Navbar, Container, Form, Button } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import Main from './routes/Main';
import { Route, Routes, useNavigate } from 'react-router-dom';
import Ranking from './routes/Ranking';
import CharacterInfo from './routes/CharacterInfo'

function App() {
  let navigate = useNavigate();

  let [name, setName] = useState('');

  let changeName = (e: any) => {
    setName(e.target.value);
  }

  let searchCharacter = () => {
    navigate('/character/' + name);
  }

  return (
    <div>
      <Navbar expand="lg">
        <Container>
          <Navbar.Brand href="/">LostArk API</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link onClick={() => { navigate('/') }}>Home</Nav.Link>
              <Nav.Link onClick={() => { navigate('/ranking') }}>Ranking</Nav.Link>
            </Nav>
            <Form className="d-flex">
            <Form.Control
              type="search"
              placeholder="캐릭터 검색"
              className="me-2"
              aria-label="Search"
              value={name}
              onChange={changeName}
            />
            <Button variant="outline-success" size="sm" onClick={() => { searchCharacter() }}>Search</Button>
          </Form>
          </Navbar.Collapse>
        </Container>
      </Navbar>

      <Routes>
        <Route path="/" element={ <Main></Main> }></Route>
        <Route path="/ranking" element={<Ranking></Ranking>}></Route>
        <Route path="/character/:name" element={<CharacterInfo></CharacterInfo>}></Route>
      </Routes>
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">LostArk API</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <router-link to="/">Home</router-link>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Ranking</a>
          </li>
        </ul>
        <form class="d-flex" role="search" @keydown.enter="searchCharacter">
          <input class="form-control me-2" type="search" placeholder="캐릭터 검색" aria-label="Search" @input="setSearchText" :value="searchText">
          <button class="btn btn-outline-success" type="submit" @click="searchCharacter">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <router-view></router-view>
</template>

<script lang="ts">
import { ref, defineComponent} from 'vue';
import router from './router';

export default defineComponent({
  name: 'App',
  setup() {
    let searchText = ref('');

    function setSearchText(e: Event) {
      let text = (e.target as HTMLInputElement).value;
      searchText.value = text;
    }

    function searchCharacter(e: any) {
      e.preventDefault();
      console.log(searchText.value);

      router.push(`/character/${searchText.value}`);
    }

    return { searchText, setSearchText, searchCharacter };
  }
})

</script>

<style>

</style>
